### ISSUE TITLE
Special characters cause exception

### ISSUE THREAD

**Issue by richardpenner** [thetron/StringScore#1]
The following strings log an exception in the console:

"Adèle" compared with "Adele"
"Ariel Pink’s Haunted Graffiti" compared with "Ariel Pink's Haunted Graffiti"

Note that in the last set of strings, there is a different apostrophe character.

The exception logged: -[__NSCFConstantString substringWithRange:]: Range or index out of bounds

**Comment by thetron** [comment]
Thanks for identifying this issue - will have a look and see if I can't find out what's going on.

**Comment by thetron** [comment]
Thanks again for providing those two test cases - there were a couple of issues that had sprung out of this. The scoring algorithm now replaces accented characters with their defaults (eg: è becomes e, for the purposes of matching), and punctuation gets stripped out.

**Comment by richardpenner** [comment]
Wow, amazingly fast turnaround. Thanks so much!
